apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-test
  template:
    metadata:
      labels:
        app: inference-test
    spec:
      containers:
        - name: albert-inference-container
          image: albert-inference-job-minikube:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: albert-inference-service
spec:
  selector:
    app: inference-test
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort